apiVersion: v1
kind: Pod
metadata:
  name: fortune
  namespace: ch06
  labels:
    app: fortune
spec:
  containers:
    - name: html-generator
      image: luksa/fortune
      volumeMounts:
        - mountPath: /var/htdocs
          name: html
    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
          name: http
  volumes:
    - name: html
      emptyDir: {}