apiVersion: v1
kind: Pod
metadata:
  name: mongodb-hostpath
  namespace: ch06
spec:
  containers:
    - name: mongodb
      image: mongo
      volumeMounts:
        - mountPath: /data/db
          name: mongodb-data
      ports:
        - containerPort: 27017
          protocol: TCP
  volumes:
    - name: mongodb-data
      hostPath:
        path: /mongodb/data