apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: ch06
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mongodb/data