apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-hostpath
  namespace: ch06
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""