apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-rs
  namespace: kubia-ch04
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubia
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia